---
- set_fact:
    query: "root[?Name==`{{vo.name}}`].IDCard[].gLiteConf[].FQANs[].FQAN[*].FqanExpr"

- name: "Ensure {{ vo.name }} groups"
  group:
    name: "{{ vo.name }}"
    state: present
    gid: "{{ vo.gid }}"
    system: false
